import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavMenu from "../components/NavMenu";

import { SessionProvider } from "next-auth/react";
import { auth } from "./(auth)/auth";
import { ThemeProvider } from "../components/ThemeProvider";
import { ModeToggle } from "@/components/ModeToggle";
import { User } from "@/components/User";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider session={session}>
            <div className="flex justify-end p-2 border-b border-gray-200 dark:border-gray-800 w-[100%] ">
              <User session={session} />
              <ModeToggle />
            </div>

            <main className="grid grid-cols-12 ">
              <div className="col-span-3">
                <NavMenu />
              </div>
              <div className="col-span-9">{children}</div>
            </main>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
